version: "2.2"
services:
  server:
    build: .
    expose:
      - "25565"
      - "25575"
    volumes:
      - './settings/eula.txt:/minecraft/eula.txt'
      - './settings/banned-ips.json:/minecraft/banned-ips.json'
      - './settings/whitelist.json:/minecraft/whitelist.json'
      - './settings/ops.json:/minecraft/ops.json'
      - './settings/banned-players.json:/minecraft/banned-players.json'
      - './settings/server.properties:/minecraft/server.properties'
      #the folder name must be the same as settings/server.properties.level-name
      - './world:/minecraft/MinecraftServer'
      - './logs:/minecraft/logs'
      #volumes specific to a forge server
      #- './mods:/minecraft/mods'
      #- './settings:/minecraft/config'
      #volumes specific to a spigot server
      #- './settings/bukkit.yml:/minecraft/bukkit.yml'
      #- './settings/spigot.yml:/minecraft/spigot.yml'
      #- './settings/commands.yml:/minecraft/commands.yml'
      #- './plugins:/minecraft/plugins'
    mem_limit: 2G
    container_name: mc
    restart: always