version: "3"
services:
  minecraft:
    build: .
    expose:
      - "25565"
    volumes:
      - '$PWD/settings/eula.txt:/minecraft/eula.txt'
      - '$PWD/settings/banned-ips.json:/minecraft/banned-ips.json'
      - '$PWD/settings/whitelist.json:/minecraft/whitelist.json'
      - '$PWD/settings/ops.json:/minecraft/ops.json'
      - '$PWD/settings/banned-players.json:/minecraft/banned-players.json'
      - '$PWD/settings/server.properties:/minecraft/server.properties'
      #the folder name must be the same as settings/server.properties.level-name
      - '$PWD/MinecraftServer:/minecraft/MinecraftServer'
      - '$PWD/logs:/minecraft/logs'
    container_name: mc
    restart: always